import Link from 'next/link';
import './global.scss';
import { poppins } from '../lib/font';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={poppins.variable}>
            <body>
                <aside>
                    <div>Top</div>
                    <nav className="menu">
                        <Link href="/discover">Discover</Link>
                        <Link href="/whitelist">WhiteList</Link>
                    </nav>
                    <div></div>
                </aside>
                <main> {children}</main>
            </body>
        </html>
    );
}
